<?php

require_once dirname(__FILE__) . '/../../../../app/libs/markdown.php';

/**
 * Test class for Markdown.
 * Generated by PHPUnit on 2012-02-22 at 10:59:09.
 */
class MarkdownTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Markdown
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Markdown;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement testMarkdownExtra_Parser().
     */
    public function testMarkdownExtra_Parser() {
        $text = <<<MARKDOWN
#Title1
## Title2 ##
###Title3 {#header3}
#### Title4 ####
#####Title5
######Title6

*[HTML]: Hyper Text Markup Language
*[W3C]:  World Wide Web Consortium

then, elsewhere in the document, write text such as:

The HTML specification is maintained by the W3C.

Title1
======

Title2
------

~~~~
Fenced code block
~~~~

> Blockquote
> Blockquote
> Blockquote

First Header  | Second Header
------------- | -------------
Content Cell  | Content Cell
Content Cell  | Content Cell

Paragraph -- *em*, **bold**, _em_, __bold__, `code`, 
[link1](http://example.com/1] <http://example.com/>, <del>HTML</del>.

| Item      | Value |
| --------- | -----:|
| Computer  | $1600 |
| Phone     |   $12 |
| Pipe      |    $1 |

[Link back to header 3](#header3)

And a paragraph with hard<br/>
breaks and more links [link2](http://example.com/2 "Link 2"), [link3](/about/),
[link4_1][id1], [link4_2][id2], [link4_3][id3], [link4_4][id4] and an implicit link
[Google][].

[id1]: http://example.com/  
[id2]: <http://example.com/>  "Optional Title Here"
[id3]: http://example.com/  'Optional Title Here'
[id4]: http://example.com/  (Optional Title Here)

        code block
        code block

Reference list links: [Google] [1], [Yahoo] [2] and [MSN] [3].

  [1]: http://google.com/        "Google"
  [2]: http://search.yahoo.com/  "Yahoo Search"
  [3]: http://search.msn.com/    "MSN Search"

+ one
+ two
+ three

That's some text with a footnote.[^1]

[^1]: And that's the footnote.

* one
* two
* three

<div markdown="1">
This is *true* markdown text.
</div>

- one
- two
- three

* * *

***

*****

- - -

---------------------------------------

![image](http://image.com/image.png "alt")

![Image alt][id]

Paragraph.

[id]: /url/to/image.png  "Optional title attribute"

1. one
1. two
1. three

def1
: item1
: item 2

Escape sequences: \\ \` \* \_ \{ \} \[ \( \) \# \+ \- \. \!

MARKDOWN;
        $result = $this->object->transform($text);
        $this->assertTrue(is_string($result));
    }
}

?>
