<?php

require_once dirname(__FILE__) . '/../../log.class.php';
require_once dirname(__FILE__) . '/../../pew.class.php';

/**
 * Test class for Log.
 * Generated by PHPUnit on 2012-01-11 at 12:16:44.
 */
class LogTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Log
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Log;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    public function testIn() {
        $this->assertNull($this->object->in('Logging test 1'));
        $this->assertNull($this->object->in('Logging test 2', 'Title'));
        $this->assertNull($this->object->in('Logging test 3', 123123));
    }

    public function testOut() {
        ob_start();
        $this->object->out();
        $result = ob_get_contents();
        ob_end_clean();
        
        $this->assertRegExp("/Logging test 1/", $result);
    }

    public function testSession()
    {        
        defined('USESESSION') or define('USESESSION', true);
        $_SESSION['test1'] = 'test_1_value';
        ob_start();
        $this->object->session();
        $result = ob_get_contents();
        ob_end_clean();
        
        $this->assertEquals("", $result);
    }

}

?>
