<?php

define('USESESSION', false);
define('USEDB', false);
define('USEAUTH', false);
define('DEFAULT_CONTROLLER', 'pages');
define('DEFAULT_ACTION', 'index');

require_once dirname(__FILE__) . '/../functions.php';
require_once dirname(__FILE__) . '/../pew_request.class.php';

/**
 * Test class for PewRequest.
 * Generated by PHPUnit on 2012-03-10 at 12:39:17.
 */
class PewRequestTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PewRequest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PewRequest;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * 
     */
    public function testConstruct()
    {
        $_GET = array();
        $_POST = array();
        $this->markTestIncomplete();
    }
    
    /**
     * 
     */
    public function testParse()
    {
        $this->object->parse('my_controller/my_action/key:value/2');
        $this->assertEquals('my_controller', $this->object->controller());
        $this->assertEquals('my_action', $this->object->action());
        $this->assertEquals(array('key' => 'value'), $this->object->named());
    }
}
